version: '3.9'
services:
  backend:
    depends_on:
      - database
    build: ./backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - APP_PORT=3001
      - JWT_SECRET=secretJWT
      #db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=database # Nome do service logo abaixo
      - MYSQL_PORT=3306
      - MYSQL_DATABASE_NAME=dbOdonto
      - PORT = 3001
      # - API_HOST: 'backend'
      # - API_PORT: 3001
      # - NODE_ENV: 'development'
    command: dev
    volumes:
      - ./backend/src:/backend/src
    networks:
      - backend-network
      
  # frontend:
  #   build: ./frontend
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - backend

  database:
    image: mysql:8.0.29
    restart: always
    environment:
      # MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge