version: '3'
services:
  backend:
    container_name: app-backend
    build: ./backend
    ports:
      - 3002:3002
    depends_on:
      - database
    restart: always
    environment:
      APP_PORT: 3002
      JWT_SECRET: secretJWT
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: localhost 
      MYSQL_PORT: 3306
      MYSQL_DATABASE_NAME: dbOdonto
      PORT: 3002
      # - API_HOST: 'backend'
      # - API_PORT: 3001
      # - NODE_ENV: 'development'
    command: dev
    working_dir: /app-backend
    volumes:
      - ./backend:/app-backend/backend
    networks:
      - backend-network
      
  # frontend:
  #   build: ./frontend
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - backend

  database:
    image: mysql:8.0.29
    container_name: dbOdonto
    ports:
      - 3306:3306
    restart: always
    environment:
      # MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge